"use client";

import { useState, useEffect } from "react";
import { AppLayout } from "@/components/layout/app-layout";
import { Card, CardContent } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { CodePreview } from "@/components/ui/code-preview";
import { Markdown } from "@/components/ui/markdown";
import { FileCode, FileText, Image, Layers } from "lucide-react";

interface Artifact {
  id: string;
  filename: string;
  fileType: string;
  mimeType: string;
  content: string;
  size: number;
  createdAt: string;
  card: { title: string };
  user: { name: string };
}

export default function ArtifactsPage() {
  const [artifacts, setArtifacts] = useState<Artifact[]>([]);
  const [filter, setFilter] = useState("all");
  const [expanded, setExpanded] = useState<string | null>(null);

  useEffect(() => {
    fetch("/api/artifacts" + (filter !== "all" ? `?type=${filter}` : ""))
      .then((r) => r.json())
      .then((d) => setArtifacts(Array.isArray(d) ? d : []))
      .catch(() => {});
  }, [filter]);

  const icons: Record<string, typeof FileCode> = {
    code: FileCode,
    document: FileText,
    image: Image,
  };

  return (
    <AppLayout>
      <div className="space-y-6">
        <div className="flex items-center justify-between">
          <div>
            <h1 className="text-2xl font-semibold text-neutral-900">
              Artifacts
            </h1>
            <p className="text-secondary">Files generated by AI agents</p>
          </div>
          <Select value={filter} onValueChange={(v) => { if (v) setFilter(v); }}>
            <SelectTrigger className="w-[150px]">
              <SelectValue />
            </SelectTrigger>
            <SelectContent>
              <SelectItem value="all">All Types</SelectItem>
              <SelectItem value="code">Code</SelectItem>
              <SelectItem value="document">Documents</SelectItem>
            </SelectContent>
          </Select>
        </div>
        <div className="space-y-3">
          {artifacts.map((a) => {
            const Icon = icons[a.fileType] || Layers;
            return (
              <Card
                key={a.id}
                className="cursor-pointer"
                onClick={() =>
                  setExpanded(expanded === a.id ? null : a.id)
                }
              >
                <CardContent className="p-4">
                  <div className="flex items-center gap-3">
                    <Icon className="h-5 w-5 text-primary shrink-0" />
                    <div className="flex-1 min-w-0">
                      <p className="text-sm font-medium truncate">
                        {a.filename}
                      </p>
                      <p className="text-xs text-secondary">
                        by {a.user.name} on &quot;{a.card.title}&quot;
                      </p>
                    </div>
                    <Badge variant="outline" className="text-xs">
                      {a.fileType}
                    </Badge>
                    <span className="text-xs text-secondary">
                      {(a.size / 1024).toFixed(1)}KB
                    </span>
                  </div>
                  {expanded === a.id && (
                    <div className="mt-3">
                      {a.fileType === "code" ? (
                        <CodePreview code={a.content} filename={a.filename} />
                      ) : a.mimeType?.includes("markdown") ? (
                        <Markdown content={a.content} />
                      ) : (
                        <pre className="text-xs bg-surface p-3 rounded-lg overflow-auto max-h-[300px]">
                          {a.content}
                        </pre>
                      )}
                    </div>
                  )}
                </CardContent>
              </Card>
            );
          })}
          {artifacts.length === 0 && (
            <p className="text-center text-secondary py-10">
              No artifacts yet
            </p>
          )}
        </div>
      </div>
    </AppLayout>
  );
}
